### ISSUE TITLE
Templates and statics are not included with 'pip install'

### ISSUE THREAD

**Issue by jeromelebleu** [moccu/django-cruditor#8]
I try to have the last revision of this application with `pip install git+git://github.com/moccu/django-cruditor.git@master`, but there are just *.py files in the package folder. It seems to be related with 64a351c2f438af11d486ebcda27392322f40b836.

**Comment by stephrdev** [comment]
Fixed in 14b2b44. You found the right place but it only affected pip installation from a git checkout when not passing the editable flag. The distributed packages and `pip install -e git+https://....` worked fine.

**Comment by jeromelebleu** [comment]
Thanks! By the way, do you have an idea of the next release date please?

**Comment by stephrdev** [comment]
Will do a release today, there are plenty new features worth putting them on pypi ;-)
